README.md
=> Minor sentence restructuring and word removal

src/helpers.php
=> check if function exists

README.md, src/Directive.php, src/Policies/Basic.php, src/Policies/Policy.php, src/Value.php, tests/AddCspHeadersTest.php
this solves https://github.com/spatie/laravel-csp/issues/25
=> add value constants

README.md, src/CspServiceProvider.php, src/helpers.php, tests/NonceTest.php
=> cspNonce to csp_nonce

README.md
=> Documented multiple policy for single addDirective

README.md, src/Policies/Policy.php, src/Value.php, tests/AddCspHeadersTest.php
Possible fix for https://github.com/spatie/laravel-csp/issues/43
=> Add possibility to change value to no value

src/Directive.php
This PR adds 4 new directives:
- style-src-attr (https://w3c.github.io/webappsec-csp/#directive-style-src-attr)
- style-src-elem (https://w3c.github.io/webappsec-csp/#directive-style-src-elem)
- script-src-attr (https://w3c.github.io/webappsec-csp/#directive-script-src-attr)
- script-src-elem (https://w3c.github.io/webappsec-csp/#directive-script-src-elem)
=> add new script and style directives

README.md
See https://github.com/spatie/laravel-csp/issues/49
=> Add note on how to use with filp/whoops

src/Directive.php
Add webrtc-src directive for [WebRTC](https://developer.mozilla.org/ru/docs/Web/API/WebRTC_API)
=> Add webrtc-src directive

src/Keyword.php
See https://content-security-policy.com/unsafe-hashes/
=> Add unsafe-hashes keywork

.gitignore, composer.json, phpunit.xml.dist
- Added .idea folder to .gitignore file.
- PHP Unit migrated configuration to new format.
- Added support for PHP 8 on composer file.
=> Added support to PHP 8

.github/workflows/run-tests.yml, composer.json, tests/AddCspHeadersTest.php, tests/BladeTest.php, tests/DirectiveTest.php, tests/NonceTest.php, tests/Pest.php, tests/TestCase.php
Hi! I've rewritten tests to use Pest instead of PHPUnit
=> Rewrite tests to use Pest

README.md
I believe it changed a few times during the PR so you probably took an early version  :)
=> Wrong method name for Vite nonce

README.md
this will fix github test workflow badge icon.
=> fix github test badge

src/CspServiceProvider.php
No clue why it stopped working but this fixes it in my Laravel 11.36.1 install.
=> Fix getting Blade compiler

UPGRADE.md
A small change here to make it easier for people upgrading
=> Update migration guide to use `$policy`

src/Presets/Clarity.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_Clarity______Spatie_Csp_Presets_Clarity__.snap, tests/PresetTest.php
as per https://spatie.be/blog/releasing-laravel-csp-3-and-a-call-for-contributors preset for Microsoft Clarity CSP Directives.
=> Add Microsoft Clarity Preset

README.md, src/Presets/MetaPixel.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_MetaPixel______Spatie_Csp_Presets_MetaPixel__.snap, tests/PresetTest.php
=> Preset for Meta Pixels

src/Presets/HotJar.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_HotJar______Spatie_Csp_Presets_HotJar__.snap, tests/PresetTest.php
This adds a preset for HotJar, which is an analytics and heatmapping tool.
=> Add HotJar preset

README.md, config/csp.php
I believe this format no longer works so I have updated the comments in the config and readme.
=> Use correct format for directives

src/Presets/Fathom.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_Fathom______Spatie_Csp_Presets_Fathom__.snap
The Fathom preset is missing `Directive::CONNECT`
=> Fathom Preset Missing Connect

src/Presets/MetaPixel.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_MetaPixel______Spatie_Csp_Presets_MetaPixel__.snap
The Meta preset is missing `Directive::CONNECT`
=> MetaPixel Preset is missing connect
