spatie/laravel-csp

config/csp.php
Google Analytics also requires `img-src` to allow its domain.
I don't really know why, but I guess it had a 1px image somewhere to allow tracking without javascript.
Anyway, without allowing it inside the CSP header, it'll return an error.
=> add google-analytics img-src to config file

.travis.yml, composer.json
In https://github.com/spatie/laravel-csp/issues/19 the question about the minimum PHP version has been raised. This PR solves it by:
* extending the min PHP version constraint
* extending the min phpunit version constraint
=> also allow php 7.0

README.md, src/Policies/Policy.php, tests/AddCspHeadersTest.php
#33 
As described in the title **PLUS** the fact that now it's possible to give multiple options separated by one or more spaces and they'll still be examined atomically, which came natural to me to prevent possible errors with hash detection: the string `sha256-hash some random text` would have been all enclosed in a single couple of quotes without this feature.
It can be easily removed if that feature isn't welcome, even if I think it can help to provide more flexibility and usability.
=> Hashes auto-enclosed into quotes

.gitignore, src/CspServiceProvider.php, tests/BladeTest.php, tests/fixtures/view.blade.php
`@nonce` blade directive inlines `csp_nonce()` call inside string and blade compiler does not call the function.
Resulting compiled output is `nonce='csp_nonce()'`
Changed directive to so that the function call is explicit.
=> FIX: blade compiler does not call csp_nonce() in @nonce directive

src/Value.php
I've simply added a new vale constant for "data:" which allows the loading of resources via the data scheme (eg Base64 encoded images).
It came about because the [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) package uses base64 encoded images for it's icons.
This is my first pull request, so if I've missed anything, please let me know!
=> Add value constant for “data:”

src/CspServiceProvider.php
The config_path method does not exist on lumen by default (we need to manually configure the configs with a method of our choice).
=> Fix lumen compatibility in console

README.md, composer.json, src/Keyword.php, src/Policies/Basic.php, src/Policies/Policy.php, src/Scheme.php, src/Value.php, tests/AddCspHeadersTest.php
**breaking**
This adds also `blob`, `http/s` scheme in addition to #38 
The renaming of the `Value` class and the move of the `data` constant are the breaking changes. I'm open for discussions and can also send a PR that adds these constants to the `Value` class to keep this open for `v2`.
=> Add scheme values

src/Directive.php
Report-to supersedes report-uri, although it is only currently supported in Chrome (and Chrome-based Edge). It would be nice to have access to both.
=> Added "report-to" directive

src/Directive.php
This PR adds the directive for `prefetch-src`, which was uncovered while integrating with plaid that uses this directive. 
> link-initialize.js:1 Refused to prefetch content from 'https://cdn.plaid.com/link/2.0.735/link-dynamic-loader.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'prefetch-src' was not explicitly set, so 'default-src' is used as a fallback.
=> add prefetch-src directive

README.md
I wasn't quite happy with the listed approaches on how to handle the CSP on debug-pages, so I added another one, which I think works quite nicely.
Since it completely deactivates the CSP on debug-pages, this approach also works with strict CSPs.
~I also changed a type (which is a breaking change). I can remove this commit if you want to.~
(This package is awesome by the way 🙇.)
=> Add new alternative for handling CSP on error-page

.github/workflows/php-cs-fixer.yml, .github/workflows/run-tests.yml, .gitignore, .php-cs-fixer.dist.php, composer.json
This fixes errors in GitHub actions, see https://github.com/spatie/laravel-csp/runs/3734009499 for example.
Details: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/UPGRADE-v3.md
* removed unsupported/outdated Laravel 5.8 and 7 version from test-matrix (`roave/security-advisories` complained about those)
* removed support for PHPUnit v8, since it is not compatible with the current phpunit XML-config
* added `fileinfo` PHP extension to fix errors on `windows-latest`
=> Make package compatible with php-cs-fixer v3

README.md
Fixing broken link and grammar issue on README
=> Fixing readme issues

src/CspServiceProvider.php
Right now this package always boots up Blade in order to register its directives, even if the app itself might not need blade to handle whatever its doing. This PR changes the bootstrapping process to wait for blade to be resolved before registering the directives. If blade was previously resolved (by another service provider or a piece of app code) the directives will be registered immediately
=> Lazily register blade directives

src/Scheme.php, tests/AddCspHeadersTest.php
Adds an extra constant `WSS` to the `Scheme` enum class to support the secure websocket protocol
I also sorted the constants in that class alphabetically to match the other classes.
=> Add wss: (secure websocket) scheme support

README.md
The link reference is no longer working. Resulting in 404 error. here is the expired link https://www.laraning.com/videos/spatie-csp-content-security-policy
=> Removed expired link from readme file

src/Directive.php
This pull request adds support for the `require-trusted-types-for` directive.
The directive is documented as follows: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for 
Browser support list: https://caniuse.com/mdn-http_headers_content-security-policy_require-trusted-types-for
=> Add require-trusted-types-for directive

.github/workflows/php-cs-fixer.yml, .github/workflows/run-tests.yml, .github/workflows/update-changelog.yml, composer.json, phpunit.xml.dist
This PR drops support for Laravel 8 and PHP 8.0, which are both EOL. It adds support for Laravel 11 and starts running tests on PHP 8.3 with Pest 2 (for Laravel 10 and 11). It also bumps some Github Action dependencies.
=> chore: prepare for laravel 11

src/Keyword.php
This pull request adds the missing Content Security Policy (CSP) keyword wasm-unsafe-eval.
`Content-Security-Policy: script-src 'wasm-unsafe-eval'`
[MDN WEb Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution)
=> feat: added missing 'wasm-unsafe-eval' keyword

.gitattributes
This ensures that the `.github` directory and `.php-cs-fixer.dist.php` file is not included in vendor releases.
=> chore: update Git Attributes

src/AddCspHeaders.php
This is #107 renewed now that PHP 8.4 will deprecate the old behavior; see also [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated).
=> Mark arguments as nullable in AddCspHeaders

config/csp.php, src/CspServiceProvider.php, src/Policies/Policy.php
This PR adds the ability to skip nonce generation when using unsafe-inline in your CSP policy. This is implemented by:
- Adding `nonce_enabled` config option (defaults to true)
- Updating Policy class to skip adding nonces when disabled
- Adding documentation about use cases and security implications
This is particularly useful when:
- Using unsafe-inline for legacy code compatibility 
- Working with third-party scripts that don't support nonces
- Debugging CSP issues
Note: Disabling nonces in favor of unsafe-inline reduces security. Only use when necessary.
=> Add ability to skip nonce generation

.github/workflows/run-tests.yml, composer.json
Laravel 12 isn't released yet, but everything is already prepared for it and so packages can already support it.
- I removed the `include:` and explicit `nesbot/carbon`/`orchestra/testbench` part completely, because it would require to always fill it in for Laravel versions, which shouldn't be necessary -> composer will resolve the appropriate versions on its own to satisfy the primary `laravel/framework` dependency anyway
=> Add support for Laravel 12

src/Policy.php, tests/AddCspHeadersTest.php
Previously in version 2, null values wouldn't cause an issue and were ignored, 
In version 3,  they do ie 
```
TypeError: Spatie\Csp\Policy::Spatie\Csp\{closure}(): Argument #1 ($value) must be of type Spatie\Csp\Keyword|string, null given in /home/runner/work/app/app/vendor/spatie/laravel-csp/src/Policy.php:37 
```
This just ensures null values are removed, I think this is straight forward enough - a use case could be: 
```php
->add(Directive::FONT, [Keyword::SELF, $this->potentialNull()]);
public function potentialNull() : ?string
```
The null method may return null in a testing environment for example. 
I've added a test to make sure there's no regression too.
=> Ensure null values are removed

README.md, src/Presets/CloudflareTurnstile.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_CloudflareTurnstile______Spatie_Csp_Presets_CloudflareTurnstile__.snap, tests/PresetTest.php
This PR adds a new preset, CloudflareTurnstile. It sets both frame-src and script-src to https://challenges.cloudflare.com - as noted by [Cloudflare's documentation](https://developers.cloudflare.com/turnstile/reference/content-security-policy/).
=> Cloudflare Turnstile preset

src/AddCspHeaders.php, tests/AddCspHeadersTest.php
I've noticed since upgrading to v3 that Laravel's built-in exception rendering functionality doesn't display correctly, as the CSP middleware is still applied in this context. 
The following screenshot is the exception rendering page in a blank Laravel 12 application using the Basic preset:
This PR skips applying the CSP middleware if the application is in debug mode, and the response contains a server error. 
This felt like the simplest solution I could come up with to the problem, although I suppose an alternative could be to create a preset for the exception rendering page and return that  CSP middleware instead of no CSP middleware whatsoever. Any thoughts on the best approach would be appreciated.
=> Skip CSP middleware when Laravel is rendering an exception

README.md, src/Presets/CloudflareWebAnalytics.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_Cloudflare…lytics______Spatie_Csp_Presets_Cloudflare___lytics__.snap, tests/PresetTest.php
This PR adds a preset for [Cloudflare Web Analytics](https://developers.cloudflare.com/web-analytics/). Documentation followed is here [https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/](https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/)
=> Add Cloudflare Web Analytics preset

UPGRADE.md
The Preset interface requires a return type of `void`, so I think it's just a typo.
=> docs: remove return from v3 upgrade guide

src/AddCspHeaders.php, tests/AddCspHeadersTest.php
This PR skips applying CSP middleware if the app is in debug mode and Vite is hot reloading, as applying CSP in this context (at least in my experience), isn't massively useful, since all the asset URLs are `http://localhost:5173`.
=> Skip CSP middleware when Vite is hot reloading

README.md, config/csp.php, src/AddCspHeaders.php, tests/AddCspHeadersTest.php
There was some discussion here about whether or not this should be always enabled, so I've added a configuration option that allows it to be toggled. https://github.com/spatie/laravel-csp/pull/154
=> Add configuration for Vite hot reloading 

src/Presets/GoogleTagManager.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_GoogleTagManager______Spatie_Csp_Presets_GoogleTagManager__.snap
Added `*.googleadservices.com` as per Google's documentation:
https://developers.google.com/tag-platform/security/guides/csp#google_ads
=> GoogleTagManager Preset Missing URL

src/Presets/GoogleAnalytics.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_GoogleAnalytics______Spatie_Csp_Presets_GoogleAnalytics__.snap
Added `pagead2.googlesyndication.com` and `td.doubleclick.net`, according to Google's documentation:
https://developers.google.com/tag-platform/security/guides/csp#google_analytics_4_google_analytics
=> GoogleAnalytics Preset Missing Some URL's

src/Policy.php
Previously we were able to override report uri using `$this->reportTo()` method inside policy.
```
class ReportOnlyContentSecurityPolicy extends Policy
{
public function configure()
{
if ($reportUri = config('csp.report_only_policy_report_uri')) {
$this->reportTo($reportUri);
}
// ...add directives...
}
}
```
This was useful for setting custom report uri for report only policy.
Since v3, it's no longer possible. This PR makes this possible again:
```
class UseReportOnlyReportUri implements Preset
{
public function configure(Policy $policy): void
{
if ($reportUri = config('csp.report_only_policy_report_uri')) {
$policy->setReportUri($reportUri);
}
}
}
```
We use Datadog for ingesting CSP violations and have no way to distinguish "enforce" vs "report-only" violations without having separate …
=> Add `Policy@setReportUri()` method

README.md, src/Nonce/NonceGenerator.php
First of all, thanks Spatie for this great package
The W3C spec clarifies why we should use a base64-value for a nonce.
Currently I get the impression: "Hey, I can create my own nonce any way I like, it just has to be randomised for each request", until I hit a `\` or `+`,... and my headers or HTML break.
I hit this small detail whilst reading through the W3C spec, unfortunately I could not find the same notices in the MDN docs.
This pull request only adds documentation
- The NonceGenerator's contract now hints the use of a base64-value as specified by the W3C spec 
- I did not see many doc-blocks through the rest of the code, so I'm not sure if I am out of line by adding one.
- The README now also hints at the usage of a base64-value
Illuminate's `Str::random()` already generates a …
=> Docs|  Hint the usage of a base64-value for generated nonces

README.md, src/Presets/Sentry.php
This pull request adds support for Sentry as a preset in the package, making it easier for users to configure Content Security Policy (CSP) rules for Sentry integrations. The main changes include updating the documentation to list Sentry as a built-in preset and introducing a new `Sentry` preset class.
**Documentation update:**
* Added Sentry to the list of available presets in the `README.md` file, including a link to sentry.io.
**New preset implementation:**
* Created a new `Sentry` preset class in `src/Presets/Sentry.php` that configures the CSP policy to allow connections to Sentry's US ingest endpoint.
=> feat: sentry preset added

README.md, src/Presets/Whereby.php
This pull request adds support for Whereby as a new Content Security Policy (CSP) preset. The main changes include the creation of a new `Whereby` preset class and updating the documentation to list Whereby among the available presets.
**New preset addition:**
* Added a new `Whereby` CSP preset by creating the `Whereby` class in `src/Presets/Whereby.php`, which configures the policy to allow scripts and frames from `https://*.whereby.com`.
**Documentation update:**
* Updated the `README.md` to include `Whereby` in the list of available presets.
=> feat: whereby CSP preset added

README.md, src/Presets/Bootstrap.php
This pull request adds a new Content Security Policy (CSP) preset for Bootstrap, making it easier to configure CSP rules for projects using Bootstrap resources. The most important changes are:
**New Bootstrap CSP Preset:**
* Added a new `Bootstrap` preset class in `src/Presets/Bootstrap.php` that configures the CSP policy to allow styles and fonts from `data:` and `https://maxcdn.bootstrapcdn.com`.
**Documentation Update:**
* Updated the `README.md` to include the new `Bootstrap` preset in the list of commonly used presets, providing visibility and usage instructions for users.
=> feat: add bootstrap preset

README.md, src/Presets/JQuery.php
This pull request adds support for a new Content Security Policy (CSP) preset for jQuery. The main changes include introducing a new `JQuery` preset class and updating the documentation to reflect its availability.
**New preset addition:**
* Added a new `JQuery` preset class in `src/Presets/JQuery.php`, which configures the CSP policy to allow scripts from `https://code.jquery.com`.
**Documentation update:**
* Updated `README.md` to include `JQuery` in the list of available CSP presets, with a link to [jquery.com](https://jquery.com).
=> feat: add jquery preset

README.md, src/Presets/HeapAnalytics.php
This pull request adds support for Heap Analytics as a new preset in the package. The main changes include the implementation of the `HeapAnalytics` preset and updating the documentation to reflect this addition.
**New Heap Analytics preset:**
* Added a new `HeapAnalytics` class in `src/Presets/HeapAnalytics.php` to define the necessary Content Security Policy (CSP) directives for Heap Analytics. This includes allowing scripts from `https://cdn.heapanalytics.com` and image/connect requests to `https://heapanalytics.com`.
**Documentation update:**
* Updated the `README.md` to include `Heap Analytics` in the list of available presets, with a link to the Heap Analytics website.
=> feat: heap analytics preset added

README.md, src/Presets/CloudflareCdn.php
This pull request adds support for Cloudflare CDN as a new preset in the package. The main changes include updating the documentation to list the new preset and introducing a new preset class that configures the appropriate Content Security Policy (CSP) directives for Cloudflare CDN.
**Cloudflare CDN preset addition:**
* Added `Cloudflare Cdn` to the list of available presets in the `README.md` documentation, including a link to the Cloudflare CDN product page.
* Introduced a new `CloudflareCdn` preset class in `src/Presets/CloudflareCdn.php`, which configures the CSP policy to allow styles and scripts from `https://cdnjs.cloudflare.com`.
=> feat: add cloudflare cdn preset

src/Presets/Vimeo.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_Vimeo______Spatie_Csp_Presets_Vimeo__.snap
This pull request updates the `Vimeo` preset configuration to improve Content Security Policy (CSP) handling by consolidating directive additions and expanding allowed sources for specific content types.
**CSP directive improvements:**
* Combined the addition of `SCRIPT` and `FRAME` directives for `'player.vimeo.com'` into a single call for cleaner code and easier maintenance.
* Added the `CONNECT` directive to allow connections to `'vimeo.com'`, supporting features that require API or data requests.
* Added the `IMG` directive to permit images from `'*.vimeocdn.com'`, ensuring embedded Vimeo content can load necessary images.
=> Fix: vimeo preset

README.md, src/Presets/SurveyMonkey.php, tests/.pest/snapshots/PresetTest/it_stringifies_with_data_set____Spatie_Csp_Presets_SurveyMonkey______Spatie_Csp_Presets_SurveyMonkey__.snap, tests/PresetTest.php
This pull request adds support for SurveyMonkey as a preset in the package, allowing users to easily configure Content Security Policy (CSP) settings for SurveyMonkey integrations. The main changes involve introducing the new `SurveyMonkey` preset, updating documentation, and adding corresponding tests.
**SurveyMonkey Preset Integration:**
* Added a new `SurveyMonkey` preset class (`src/Presets/SurveyMonkey.php`) that configures the CSP to allow framing from `https://www.surveymonkey.com`.
* Updated the list of available presets in the documentation to include SurveyMonkey (`README.md`).
**Testing:**
* Added the `SurveyMonkey` preset to the preset test suite (`tests/PresetTest.php`).
* Added a snapshot test to verify the CSP stringification for the `SurveyMonkey` preset …
=> Feat: add SurveyMonkey preset
